### ISSUE TITLE
Update function named parameters description in docs comment 

### ISSUE THREAD

**Issue by phamhieu** [supabase/postgrest-dart#11]
# Improve documentation

## Describe the problem

Thanks to @duythien0912 work on issue #6, the functions are easier-to-understand. 

We need help with updating the  docs comment to reflect these new named parameters.

## Describe the improvement

![95757842-da979f00-0cd1-11eb-8bdf-4061aac4c75f](https://user-images.githubusercontent.com/689843/95833650-868ec800-0d6e-11eb-9186-eabce72c95bb.png)

can be updated to:  ```You can also provide `headers` and `schema` parameters if needed```

## Additional context

These are the old functions that have been refactored. We need to check the descriptions of each function and update them.

```dart
PostgrestClient(String url, [Map<String, dynamic> options = const {}])

PostgrestBuilder insert(dynamic values, [Map options = const {'upsert': false}]) 

PostgrestTransformBuilder order(String column, [Map options = const {'ascending': false, 'nullsFirst': false, 'foreignTable': null}])

PostgrestTransformBuilder limit(int count, [Map options = const {'foreignTable': null}])

PostgrestTransformBuilder range(int from, int to, [Map options = const {'foreignTable': null}])

PostgrestFilterBuilder fts(String column, String query, [Map options = const {'config': null}])

PostgrestFilterBuilder plfts(String column, String query, [Map options = const {'config': null}])

PostgrestFilterBuilder phfts(String column, String query, [Map options = const {'config': null}])

PostgrestFilterBuilder wfts(String column, String query, [Map options = const {'config': null}])
```

**Comment by akhil2000mittal** [comment]
@phamhieu i can help you with that
