### ISSUE TITLE
insert, update and delete return 301 when executed

### ISSUE THREAD

**Issue by amitkhairnar44** [supabase/postgrest-dart#15]
# Bug report

## Describe the bug

Some functions seem to return `301` status when executed. I have tried the `select` function and it's working properly but other don't work as intended. I'm able to fetch the data from the Postgrest DB but unable to update, insert or delete any row.

Code that I'm using
```dart
    var _client = PostgrestClient(postgRestEndpoint,
        schema: 'public', headers: {'apikey': apiKey});

    var response = await _client.from('Users').insert([
      {'name': 'Some User', 'email': 'someuser@example.com'}
    ]).execute();
```

## Expected behaviour
A new row should be inserted in the Postgrest DB.

**Comment by kiwicopple** [comment]
Hey @amitkhairnar44 , you shouldn't need the `execute()`. https://supabase.io/docs/client/insert

If you remove it, hopefully that fixes the problem. I'll close this for now, but feel free to reopen if you are still experiencing difficulties

**Comment by amitkhairnar44** [comment]
@kiwicopple But the README.md says to execute it.

I'll try it without 'execute()' and check.

**Comment by phamhieu** [comment]
> I'm able to fetch the data from the Postgrest DB but unable to update, insert or delete any row.

Hi @amitkhairnar44, can you share the error message? you can get it with `response.error.message`. I tested on my end and i could be able to insert, update and delete.

I published a new version; only contains lint error fix so i don't think it's related. But you can give it a try.

> you shouldn't need the execute()

@kiwicopple we need `execute()` to end the query chain like in python lib.

**Comment by amitkhairnar44** [comment]
> > I'm able to fetch the data from the Postgrest DB but unable to update, insert or delete any row.
> 
> 
> 
> Hi @amitkhairnar44, can you share the error message? you can get it with `response.error.message`. I tested on my end and i could be able to insert, update and delete.
> 
> 
> 
> I published a new version; only contains lint error fix so i don't think it's related. But you can give it a try.
> 
> 
> 
> > you shouldn't need the execute()
> 
> 
> 
> @kiwicopple we need `execute()` to end the query chain like in python lib.

@phamhieu Sure, I'll try and let you know.

**Comment by amitkhairnar44** [comment]
@phamhieu It's returning `response.error` as null
`response.toJson()` returns: ` {data: , status: 301, statusText: null, error: null}`

**Comment by amitkhairnar44** [comment]
Issue has been fixed  👍
