### ISSUE TITLE
Is this production ready?

### ISSUE THREAD

**Issue by najibghadri** [supabase/postgrest-dart#18]
Dear maintainers! I'd like to know if I can use the dart client for queries rpcs and authentication without worries or is this still unstable? Thank you!

**Comment by phamhieu** [comment]
Hi @najibghadri, there will be no breaking change on the code base. If you encounter any bug or have new feature request, feel free to open issue or PR. 

Welcome to join our community discussion [here](https://github.com/supabase/supabase/discussions).

**Comment by najibghadri** [comment]
Thank you @phamhieu !
