### ISSUE TITLE
Complete test coverage

### ISSUE THREAD

**Issue by phamhieu** [supabase/postgrest-dart#2]
This is a Hacktoberfest task! 
You can read more about Hacktoberfest [on our blog](https://supabase.io/blog/2020/09/11/supabase-hacktoberfest-2020) and see all tasks on our [Hacktoberfest Project Board](https://github.com/orgs/supabase/projects/5).

# Summary

We need help with completing test coverage for this library. Following [postgrest-js](https://github.com/supabase/postgrest-js) there are 4 test files:
- basic_test.dart 
- filter_test.dart 
- resource-embedding_test.dart 
- transforms_test.dart 

Right now, there's only 1 test per file as example. We need to have all test cases as original `postgrest-js` project. 

https://github.com/supabase/postgrest-js/blob/master/test/basic.test.ts
https://github.com/supabase/postgrest-js/blob/master/test/filters.test.ts
https://github.com/supabase/postgrest-js/blob/master/test/resource-embedding.test.ts
https://github.com/supabase/postgrest-js/blob/master/test/transforms.test.ts

# Details

Before running test file, It's required to start a docker instance first:

1. Install [Docker](https://www.docker.com/)
2. `cd test/db`
3. `make start`

**Comment by asaravindkumar** [comment]
can you give me a sample of how to call Rpc method? 

    var res = await postgrest.rpc('get_status', {'username': 'supabot'}).end();
 This gives 500 error as below

{body: null, status: 500, statusCode: StateError, statusText: Bad state: Cannot set the body fields of a Request with content-type "application/json".}

**Comment by phamhieu** [comment]
@asaravindkumar good catch!

I pushed a fix for this. In short, `dart:http` requires body to be a json encoded string.

**Comment by phamhieu** [comment]
Just a head up @asaravindkumar, ~~this task is depended on #7 because the PR will convert return data into a `PostgrestResponse` obj instead of raw `Map` obj~~

#7 is already merged. Let me know if you want to work on this task @asaravindkumar.

**Comment by asaravindkumar** [comment]
@phamhieu yes. I can work on this one. thanks

**Comment by asaravindkumar** [comment]
Thanks @phamhieu.

How would you want to treat errors from tests? shall I post here? or comment the expect part for now with a TODO?

For e.g., statusText is now string, so unable to get the error code.

statusText: {"hint":null,"details":null,"code":"42P01","message":"relation \"public.missing_table\" does not exist"}

**Comment by phamhieu** [comment]
can you get error code from `error` variable?

![Screenshot 2020-10-04 at 4 25 19 PM](https://user-images.githubusercontent.com/689843/95010728-3cb32d00-065e-11eb-9de5-0df97f67bb37.png)

![Screenshot 2020-10-04 at 4 26 15 PM](https://user-images.githubusercontent.com/689843/95010742-581e3800-065e-11eb-8552-c50d341adea0.png)
