### ISSUE TITLE
jsonb imported via webui is returned as escaped string instead of JSON

### ISSUE THREAD

**Issue by nstrelow** [supabase/postgrest-dart#20]
# Bug report

## Describe the bug

jsonb column returned String after creation.
When updating the value, the client now returns Map or List instead of String.

## To Reproduce

1. Create table using csv import in webui with jsonb columns
2. Fetch the table using supabase-dart/postgrest-dart => Returns jsonb as String
3. Upsert row with .insert(Map<String, dynamic), providing a Map for `insert(values)`
4. Fetch updated table => Returns Map and List types instead of String

## Expected behavior

Always return the same type.

I would prefer this SDK to cast everything to Map<String, dynamic> or List<Map<String, dynamic>>.
But only string would be fine too,

**Comment by nstrelow** [comment]
More information:

The API returns a escaped string instead of a json object.
```
"{\"organization\":\"wertr\",\"institutionalReviewBoard\":\"wetr\",\"institutionalReviewBoardNumber\":\"wetryt\",\"researchers\":\"wetry\",\"email\":\"aefsgrdt@htfy.rfgr\"
```
my updated objects are returned without escaping and as a Map:
```
{"email": "aefsgrdt@htfy.rfgr", "phone": "123456", "website": "wtrey.ert", "researchers": "wetry", "organization": "wertr", "institutionalReviewBoard": "wetr", "institutionalReviewBoardNumber": "wetryt"}
```

I assume the distinction happens somewhere in the http library. Maybe depending on if it finds escaped chars or not.

**Comment by nstrelow** [comment]
### Workaround
In webUi
1. Open one JSONB in the editor
2. Press apply

Repeat with all columns in question. You can see the change, when the order of the JSON Map changes.

This sadly did not help
```sql
ALTER TABLE "study" ALTER COLUMN contact TYPE jsonb USING contact::text::jsonb;
```

**Comment by phamhieu** [comment]
This sounds like a bug in the webui on `csv import` which stores the jsonb value in string format.

> I would prefer this SDK to cast everything to Map<String, dynamic> or List<Map<String, dynamic>>

yes, this lib does json parsing before returns the data value. [Here](https://github.com/supabase/postgrest-dart/blob/a1db368fc59d952a764dddeacd83061ab5f34595/lib/src/postgrest_builder.dart#L103)
