### ISSUE TITLE
Fix lint errors

### ISSUE THREAD

**Issue by phamhieu** [supabase/postgrest-dart#3]
This is a Hacktoberfest task! 
You can read more about Hacktoberfest [on our blog](https://supabase.io/blog/2020/09/11/supabase-hacktoberfest-2020) and see all tasks on our [Hacktoberfest Project Board](https://github.com/orgs/supabase/projects/5).

# Summary

We need help with fixing lint errors on the source code.

## Details

By running `dartanalyzer lib/postgrest.dart`, you can see all lint errors.

![Screenshot 2020-10-01 at 10 38 19 AM](https://user-images.githubusercontent.com/689843/94759461-8d165a80-03d2-11eb-8db5-5d89f3c850f3.png)

**Comment by asaravindkumar** [comment]
Please assign this to me. i have raised a PR

**Comment by asaravindkumar** [comment]
Hi, I have created a PR for this.
