### ISSUE TITLE
Create PostgrestResponse class

### ISSUE THREAD

**Issue by phamhieu** [supabase/postgrest-dart#4]
# Feature request

## Is your feature request related to a problem? Please describe.

Right now, the library returns a `Future<Map<String, dynamic>>` response object. It'll be more convenient for us to have a response with custom class.

## Describe the solution you'd like

Follow [postgrest-js](https://github.com/supabase/postgrest-js), we want to have a response class as below:

```dart
class PostgrestError {
  String message;
  String details;
  String hint;
  String code;
}

class PostgrestResponse {
  PostgrestError error;
  int status;
  String statusText;
  dynamic body;
}
```

**Comment by duythien0912** [comment]
😆 I would like to take this issue too could you assign me ^^

**Comment by soedirgo** [comment]
@phamhieu This is a bit late but I think `body` should be `data` following https://github.com/supabase/supabase-js/issues/32, `body` was only there for backward compat.

It's a bit of a nitpick, but will save us some work in the future if we want consistent format across languages.

**Comment by phamhieu** [comment]
Thanks @soedirgo for pointing that out. I will take care of it in the next refactor commit.
