### ISSUE TITLE
X-Client-Info header

### ISSUE THREAD

**Issue by dshukertjr** [supabase/postgrest-dart#40]
Related to https://github.com/supabase/supabase-dart/issues/45

**Comment by bdlukaa** [comment]
cool

**Comment by dshukertjr** [comment]
I feel like we should discuss how we should go about implementing this, and I am not sure which option might be the best, so I took off the assignment. 

I thought we could do something similar to `postgrest-js` package where we create a `const` variable named `version` at build time. It seems like this would be possible with [pubspec_generator](https://pub.dev/packages/pubspec_generator). 

With this, I thought we might be able to setup Github actions to automatically run the build command to generate `version.dart` that contains `const version = '[current_version]'` and then publish the package automatically using [Dart and Flutter Package Publisher](https://github.com/marketplace/actions/dart-and-flutter-package-publisher). I was thinking something like [this](https://github.com/dshukertjr/postgrest-dart/blob/fix/client-info/.github/workflows/main.yml). 

The concern I have is that automating publishing packages is not recommended by the dart team at the moment.
https://github.com/dart-lang/pub/issues/2227

What do you guys think @bdlukaa @phamhieu ?

**Comment by dshukertjr** [comment]
I guess worst case we can just have a `version.dart` file that we manually update every time we publish a new package.
