### ISSUE TITLE
Dart Inner Join Filter

### ISSUE THREAD

**Issue by jtkeyva** [supabase/postgrest-dart#54]
I feel it's a basic need to be able to filter an inner join. In the words of your documentation:
If you want to filter a table based on a child table's values you can use the !inner() function. For example, if you wanted to select all rows in a message table which belong to a user with the username "Jane".

Your Documentation says not yet implemented
https://supabase.com/docs/reference/dart/select#filtering-with-inner-joins

Alternative: GraphQL

This seems like a must have feature and surprised it's not available. Having it in the documentation as a teaser stings because there is no mention of when it will be implemented.

Thanks

**Comment by dshukertjr** [comment]
@jtkeyva Thanks for opening this issue! Let me work on bringing this feature to Dart!

**Comment by dshukertjr** [comment]
@jtkeyva 
Actually, inner join feature is actually available with Dart, but the doc had an error and made it seem like it was unavailable for Dart. 

You could use it like this:

```dart
final res = await supabase
  .from('messages')
  .select('*, users!inner(*)')
  .eq('users.username', 'Jane')
  .execute();
```

Here is a PR to fix the docs
https://github.com/supabase/supabase/pull/5333

**Comment by jtkeyva** [comment]
Thank you! @dshukertjr

**Comment by kaboc** [comment]
When did it become available?  I think that all new features, or at least only important and highly convenient ones like this, should be announced in CHANGELOG.md IMHO. It is shown in the pub.dev and will be very helpful for users. I personally depend on the info on the page.

**Comment by dshukertjr** [comment]
@kaboc 
Thank you for the feedback, and yes I agree that we need a better way of communicating these cool updates to the community. This particular update was on done the backend, so there was no update on the `postgrest_dart` side of things is the tough part for this particular update. 

I will try to come up with a way of communicating these backend updates to the community, but would you happen to have any suggestions for updates like these?

**Comment by kaboc** [comment]
@dshukertjr 
I see. It's understandable. How about simply mentioning an update in the first version after it is done on the backend?
e.g. "feat (backend): `!inner` available in both latest and older versions" (+ tiny example code or a link to PR / API doc / website)

**Comment by dshukertjr** [comment]
@kaboc That is a nice idea! Will try to do that in the future!
