### ISSUE TITLE
Documentation not found

### ISSUE THREAD

**Issue by verkit** [supabase/postgrest-dart#55]
The documentation about postgrest at this [package](https://pub.dev/packages/postgrest) is not found. You said that the documentation can find from [here](https://supabase.io/docs/postgrest/client/postgrest-client).

**Comment by dshukertjr** [comment]
@verkit 
Thank you for flagging this to us! I have submitted an PR to fix this. I'm sure you are aware of this, but you can find the Dart doc [here](https://supabase.com/docs/reference/dart/select).
