### ISSUE TITLE
Add createTable method on client

### ISSUE THREAD

**Issue by jakub-stefaniak** [supabase/postgrest-dart#74]
It would be useful to let developer create tables in a declerative way.

**Comment by bdlukaa** [comment]
I don't think it's safe to create a table on the client

**Comment by dshukertjr** [comment]
@jakub-stefaniak 

As @bdlukaa has suggested, it is not safe to be able to create tables from a client, and it is not how systems are designed using [RDMS](https://www.tutorialspoint.com/Relational-Database-Management-System-RDMS). 

Typically, you want to create the table in a safe environment, like Supabase dashboard, and define/ restrict how and which rows users can access those data.

You can read more on how you can design tables from [here](https://supabase.com/docs/guides/database/tables), but I would like to close this issue for now. Feel free to open other issues if you have any questions regarding anything about Supabase!
