### ISSUE TITLE
Insert returning

### ISSUE THREAD

**Issue by programmador** [supabase/postgrest-dart#79]
As I understand there's no such a capability currently.
Though it's present in postgrest-js https://github.com/supabase/postgrest-js/issues/143

**Comment by programmador** [comment]
Oh it seems like execute() already returns all the fields! Sorry for disturbing :-)

**Comment by HankG** [comment]
PR #80 broke this behavior so it always returns nothing since the new default is "minimal" but the argument for overriding it was accidentally taken out when they broke out insert and upsert. I've submitted PR #87 to add that back.
