### ISSUE TITLE
data streaming notifications on database changes.

### ISSUE THREAD

**Issue by formvoltron** [supabase/postgrest-dart#9]
I thought Supabase was meant to be a 'host it yourself' Firebase replacement.  Which sounds great.

Only this library doesn't seem to have any of that functionality.  At least there is no such features shown in the example code or the first page github docs.

**Comment by kiwicopple** [comment]
Hey @formvoltron thanks for your question. This library is just one small part of a larger system. Check out the "How it works" here: https://github.com/supabase/supabase#how-it-works

Each part of Supabase can be hosted and in the future we will create scripts to deploy all the infrastructure yourself. 

I'll close this one now, but feel free to re-open it if you have more questions (or ask in our Q&A Discussions: https://github.com/supabase/supabase/discussions)

**Comment by awalias** [comment]
specifically on dart - 

this repo is just the CRUD component of what will be a larger lib called `supabase-dart`
<img width="508" alt="image" src="https://user-images.githubusercontent.com/458736/95033926-759ce180-06f2-11eb-9612-499318ff89c0.png">

what you're looking for is `realtime-dart` which has not yet been implemented

we do have a javascript version (https://github.com/supabase/realtime-js , which is also wrapped as part of https://github.com/supabase/supabase-js) and also a python version (https://github.com/supabase/realtime-py) for the time being in case you find them useful

**Comment by Sun3** [comment]
Looking forward to the realtime subscriptions for Dart.

**Comment by formvoltron** [comment]
Aha.  So I wasn't going crazy.  Yes the real-time stuff is what we want in
dart land.

Sockets and streaming events?  How hard can it be?

**Comment by phamhieu** [comment]
Hi @formvoltron, good news I already start working on realtime-dart package. I will let you know when it's ready.
